version: "3.9"

services:
  db:
    image: postgres:16.1
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432

  backend:
    build: ./backend
    container_name: backend
    command: uvicorn src.main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    depends_on:
      - db